### ISSUE TITLE
[PLG:APR] Primary Key Value Error

### ISSUE THREAD

**Issue by csmith73** [invenhost/plugins#20]
Matt, I upgraded Inventree to 14.1 and the approvals plugin to the latest release .5a0. I am getting the following error now when trying to start an approval or issue a PO. Any ideas?

`
ValueError
Path:
/api/order/po/74/issue/
Info:
'Approval' instance needs to have a primary key value before this relationship can be used.
When:
March 5, 2024, 11:53 p.m.
Data:
Traceback (most recent call last):

File "/root/.local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/rest_framework/generics.py", line 190, in post
return self.create(request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/InvenTree/InvenTree/mixins.py", line 22, in create
self.perform_create(serializer)

File "/root/.local/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
serializer.save()

File "/home/inventree/InvenTree/order/serializers.py", line 318, in save
order.place_order()

File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
return func(*args, **kwds)
^^^^^^^^^^^^^^^^^^^

File "/home/inventree/InvenTree/order/models.py", line 609, in place_order
return self.handle_transition(
^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/InvenTree/generic/states/transition.py", line 81, in handle_transition
rslt = override.transition(
^^^^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/inventree_approval/ApprovalPlugin.py", line 180, in transition
approval = Approval.objects.create(
^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
obj.save(force_insert=True, using=self.db)

File "/usr/local/lib/python3.11/site-packages/inventree_approval/models.py", line 221, in save
self.check_approval_state(no_save=True)

File "/usr/local/lib/python3.11/site-packages/inventree_approval/models.py", line 279, in check_approval_state
decisions = self.decisions.all()
^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 164, in all
return self.get_queryset()
^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 718, in get_queryset
raise ValueError(

ValueError: 'Approval' instance needs to have a primary key value before this relationship can be used.`

**Comment by matmair** [comment]
@csmith73 Should be fixed in 0.5a1 - please close this if you can confirm

**Comment by csmith73** [comment]
Yes approvals plugin update .5a1 fixed it. Thank you!
